# Generated by Django 5.0.1 on 2024-01-17 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=255)),
                ('versionCode', models.IntegerField()),
                ('url', models.TextField()),
                ('icon', models.TextField()),
                ('description', models.TextField()),
                ('isPublished', models.BooleanField(verbose_name=False)),
                ('isFree', models.BooleanField(verbose_name=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.apptype')),
            ],
        ),
    ]
